import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import Category from 'App/Models/Category'
import Question from 'App/Models/Question'

export default class extends BaseSeeder {
  private getCategoryIdByLabel(categories, label: string): number | undefined {
    return categories.find((t) => t.label === label)?.id
  }
  public async run() {
    const categories = await Category.all()
    // Write your database queries inside the run method
    await Question.updateOrCreateMany('label', [
      {
        label: 'Quel est le plus grand océan de la Terre?',
        categoryId: this.getCategoryIdByLabel(categories, 'Géographie'),
        answer: 'Océan Pacifique',
        choice1: 'Océan Atlantique',
        choice2: 'Océan Indien',
        choice3: 'Océan Arctique',
        correct: 0,
        count: 0,
      },
      {
        label: 'Quelle est la capitale de la France?',
        categoryId: this.getCategoryIdByLabel(categories, 'Géographie'),
        answer: 'Paris',
        choice1: 'Londres',
        choice2: 'Berlin',
        choice3: 'Madrid',
        correct: 0,
        count: 0,
      },
      {
        label: 'Quel est le plus haut sommet du monde?',
        categoryId: this.getCategoryIdByLabel(categories, 'Géographie'),
        answer: 'Mont Everest',
        choice1: 'Mont Kilimandjaro',
        choice2: 'Mont McKinley',
        choice3: 'Mont Fuji',
        correct: 0,
        count: 0,
      },
      {
        label: 'Quel pays est le plus grand en superficie?',
        categoryId: this.getCategoryIdByLabel(categories, 'Géographie'),
        answer: 'Russie',
        choice1: 'Canada',
        choice2: 'États-Unis',
        choice3: 'Chine',
        correct: 0,
        count: 0,
      },
      {
        label: 'Quelle est la plus longue rivière du monde?',
        categoryId: this.getCategoryIdByLabel(categories, 'Géographie'),
        answer: 'Amazone',
        choice1: 'Nil',
        choice2: 'Mississippi',
        choice3: 'Yangtsé',
        correct: 0,
        count: 0,
      },
      {
        label: 'Qui a peint la Joconde?',
        categoryId: this.getCategoryIdByLabel(categories, 'Art et littérature'),
        answer: 'Leonard de Vinci',
        choice1: 'Pablo Picasso',
        choice2: 'Vincent van Gogh',
        choice3: 'Claude Monet',
        correct: 0,
        count: 0,
      },
      {
        label: "Quel écrivain a écrit 'Les Misérables'?",
        categoryId: this.getCategoryIdByLabel(categories, 'Art et littérature'),
        answer: 'Victor Hugo',
        choice1: 'Charles Dickens',
        choice2: 'Fyodor Dostoevsky',
        choice3: 'Jane Austen',
        correct: 0,
        count: 0,
      },
      {
        label: "Quelle pièce de Shakespeare commence par 'Être ou ne pas être'?",
        categoryId: this.getCategoryIdByLabel(categories, 'Art et littérature'),
        answer: 'Hamlet',
        choice1: 'Macbeth',
        choice2: 'Roméo et Juliette',
        choice3: 'Othello',
        correct: 0,
        count: 0,
      },
      {
        label: "Qui a écrit la symphonie 'La Neuvième'?",
        categoryId: this.getCategoryIdByLabel(categories, 'Musique'),
        answer: 'Ludwig van Beethoven',
        choice1: 'Wolfgang Amadeus Mozart',
        choice2: 'Johann Sebastian Bach',
        choice3: 'Pyotr Ilyich Tchaikovsky',
        correct: 0,
        count: 0,
      },
      {
        label: "Quel groupe a interprété 'Stairway to Heaven'?",
        categoryId: this.getCategoryIdByLabel(categories, 'Musique'),
        answer: 'Led Zeppelin',
        choice1: 'The Beatles',
        choice2: 'The Rolling Stones',
        choice3: 'Queen',
        correct: 0,
        count: 0,
      },
      {
        label: "Quel est l'instrument principal dans une symphonie?",
        categoryId: this.getCategoryIdByLabel(categories, 'Musique'),
        answer: 'Violon',
        choice1: 'Flûte',
        choice2: 'Trompette',
        choice3: 'Clarinette',
        correct: 0,
        count: 0,
      },
      {
        label: 'Quel joueur de tennis a remporté le plus de titres du Grand Chelem?',
        categoryId: this.getCategoryIdByLabel(categories, 'Sports'),
        answer: 'Margaret Court',
        choice1: 'Serena Williams',
        choice2: 'Roger Federer',
        choice3: 'Rafael Nadal',
        correct: 0,
        count: 0,
      },
      {
        label: "Quel pays a remporté le plus de médailles d'or aux Jeux olympiques d'été?",
        categoryId: this.getCategoryIdByLabel(categories, 'Sports'),
        answer: 'États-Unis',
        choice1: 'Chine',
        choice2: 'Russie',
        choice3: 'Allemagne',
        correct: 0,
        count: 0,
      },
      {
        label: 'Quel est le plus grand tournoi de golf annuel?',
        categoryId: this.getCategoryIdByLabel(categories, 'Sports'),
        answer: 'The Masters',
        choice1: 'The Open Championship',
        choice2: 'PGA Championship',
        choice3: 'U.S. Open',
        correct: 0,
        count: 0,
      },
      {
        label: "Quel joueur de basket-ball est souvent appelé 'The King'?",
        categoryId: this.getCategoryIdByLabel(categories, 'Sports'),
        answer: 'LeBron James',
        choice1: 'Michael Jordan',
        choice2: 'Kobe Bryant',
        choice3: 'Stephen Curry',
        correct: 0,
        count: 0,
      },
      {
        label: "Dans quel sport les termes 'strike' et 'spare' sont-ils utilisés?",
        categoryId: this.getCategoryIdByLabel(categories, 'Sports'),
        answer: 'Bowling',
        choice1: 'Golf',
        choice2: 'Tennis',
        choice3: 'Baseball',
        correct: 0,
        count: 0,
      },
      {
        label: "Quelle est la capitale de l'Égypte?",
        categoryId: this.getCategoryIdByLabel(categories, 'Histoire'),
        answer: 'Le Caire',
        choice1: 'Alexandrie',
        choice2: 'Gizeh',
        choice3: 'Louxor',
        correct: 0,
        count: 0,
      },
      {
        label: 'En quelle année la Révolution française a-t-elle commencé?',
        categoryId: this.getCategoryIdByLabel(categories, 'Histoire'),
        answer: '1789',
        choice1: '1776',
        choice2: '1804',
        choice3: '1848',
        correct: 0,
        count: 0,
      },
      {
        label: 'Quel explorateur a réalisé le premier tour du monde?',
        categoryId: this.getCategoryIdByLabel(categories, 'Histoire'),
        answer: 'Ferdinand Magellan',
        choice1: 'Christopher Columbus',
        choice2: 'Marco Polo',
        choice3: 'James Cook',
        correct: 0,
        count: 0,
      },
      {
        label: 'Quel événement a marqué le début de la Première Guerre mondiale?',
        categoryId: this.getCategoryIdByLabel(categories, 'Histoire'),
        answer: "L'assassinat de l'archiduc François-Ferdinand",
        choice1: 'Le traité de Versailles',
        choice2: 'La bataille de la Marne',
        choice3: 'La prise de la Bastille',
        correct: 0,
        count: 0,
      },
      {
        label: 'Quel empire a été dirigé par Jules César?',
        categoryId: this.getCategoryIdByLabel(categories, 'Histoire'),
        answer: 'Empire romain',
        choice1: 'Empire grec',
        choice2: 'Empire ottoman',
        choice3: 'Empire perse',
        correct: 0,
        count: 0,
      },
      {
        label: "Quel jeu vidéo est souvent associé à l'icône 'Mario'?",
        categoryId: this.getCategoryIdByLabel(categories, 'Jeux vidéo'),
        answer: 'Super Mario Bros.',
        choice1: 'The Legend of Zelda',
        choice2: 'Final Fantasy',
        choice3: 'Minecraft',
        correct: 0,
        count: 0,
      },
      {
        label: 'Quelle franchise de jeux vidéo est centrée sur les combats entre véhicules?',
        categoryId: this.getCategoryIdByLabel(categories, 'Jeux vidéo'),
        answer: 'Mario Kart',
        choice1: 'Call of Duty',
        choice2: "Assassin's Creed",
        choice3: 'FIFA',
        correct: 0,
        count: 0,
      },
      {
        label:
          "Quel personnage emblématique est le héros de la série de jeux 'The Legend of Zelda'?",
        categoryId: this.getCategoryIdByLabel(categories, 'Jeux vidéo'),
        answer: 'Link',
        choice1: 'Mario',
        choice2: 'Sonic',
        choice3: 'Master Chief',
        correct: 0,
        count: 0,
      },
      {
        label: "Dans quel jeu vidéo le personnage principal s'appelle Nathan Drake?",
        categoryId: this.getCategoryIdByLabel(categories, 'Jeux vidéo'),
        answer: 'Uncharted',
        choice1: 'Tomb Raider',
        choice2: "Assassin's Creed",
        choice3: 'Gears of War',
        correct: 0,
        count: 0,
      },
      {
        label:
          'Quelle série de télévision met en scène des personnages vivant à Westeros et Essos?',
        categoryId: this.getCategoryIdByLabel(categories, 'Télévision'),
        answer: 'Game of Thrones',
        choice1: 'Breaking Bad',
        choice2: 'The Sopranos',
        choice3: 'Stranger Things',
        correct: 0,
        count: 0,
      },
      {
        label: "Qui a joué le rôle de Walter White dans la série 'Breaking Bad'?",
        categoryId: this.getCategoryIdByLabel(categories, 'Télévision'),
        answer: 'Bryan Cranston',
        choice1: 'Matthew McConaughey',
        choice2: 'Jon Hamm',
        choice3: 'Jeffrey Dean Morgan',
        correct: 0,
        count: 0,
      },
      {
        label:
          "Quelle série de science-fiction met en vedette un docteur voyageant à travers le temps et l'espace?",
        categoryId: this.getCategoryIdByLabel(categories, 'Télévision'),
        answer: 'Doctor Who',
        choice1: 'Stranger Things',
        choice2: 'The X-Files',
        choice3: 'Black Mirror',
        correct: 0,
        count: 0,
      },
      {
        label:
          "Quel est le nom du bar où les personnages de 'How I Met Your Mother' se retrouvent souvent?",
        categoryId: this.getCategoryIdByLabel(categories, 'Télévision'),
        answer: "MacLaren's Pub",
        choice1: 'Central Perk',
        choice2: "Paddy's Pub",
        choice3: 'Cheers',
        correct: 0,
        count: 0,
      },
      {
        label:
          'Quel acteur a joué le rôle de Tony Stark / Iron Man dans le Marvel Cinematic Universe?',
        categoryId: this.getCategoryIdByLabel(categories, 'Cinéma'),
        answer: 'Robert Downey Jr.',
        choice1: 'Chris Hemsworth',
        choice2: 'Chris Evans',
        choice3: 'Mark Ruffalo',
        correct: 0,
        count: 0,
      },
      {
        label: "Qui a réalisé le film 'Inception'?",
        categoryId: this.getCategoryIdByLabel(categories, 'Cinéma'),
        answer: 'Christopher Nolan',
        choice1: 'Quentin Tarantino',
        choice2: 'Steven Spielberg',
        choice3: 'Martin Scorsese',
        correct: 0,
        count: 0,
      },
    ])
  }
}
